### ISSUE TITLE
Gatsby support

### ISSUE THREAD

**Issue by tenphi** [calebdwilliams/jsx-native-events#9]
Hi! Thanks for the plugin. Do you have any idea how to add it to a Gatsby-based website?

**Comment by calebdwilliams** [comment]
I don’t have a ton of experience with Gatsby, but I imagine it’s more or less the same idea. [This post from the Gatsby site](https://www.gatsbyjs.org/blog/2019-08-02-what-is-jsx-pragma/) will probably walk you through it better than I can. 

Take a look at that an let me know if it works. If not we can figure it out together.

**Comment by tenphi** [comment]
My mistake. I asked the wrong question.

Your plugin works great with Gatsby. I just tried to find a way to remove the following code from every file:

```javascript
/** @jsx nativeEvents */
import nativeEvents from 'jsx-native-events'
```

It tried a few tricks but still don't have any idea how to do it.

**Comment by calebdwilliams** [comment]
Hey, sorry I missed this comment, but yeah you _should_ be able to add a pragma somewhere in your Babel config? There's the second paragraph of [this section of the README](https://github.com/calebdwilliams/jsx-native-events#usage). To be honest, I haven't tried that, but React says it should work so /shrug.

I'm closing this as not an issue. Let me know if you've figured anything out.
